name: nightly-forecast
on:
  push:
  schedule:
    - cron: '0 12 * * *'   # ~09:00 America/Santiago
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          pip install -r requirements.txt || \
          pip install -r upgrade_precision/requirements_min.txt || \
          pip install pandas numpy statsmodels pmdarima
      - name: Run pipeline + capture metrics
        run: |
          mkdir -p out
          python _run_and_capture_metrics.py \
            --target data/precio_huevo_mensual.csv \
            --bt_init 12 --seasonality 12 --h 2 \
            --lags 1 \
            --out out/forecast_next2m.csv
      - name: Commit artifacts (forecast + metrics)
        run: |
          git config user.name "autobot"
          git config user.email "actions@users.noreply.github.com"
          git add out/forecast_next2m.csv out/metrics.json || true
          git commit -m "auto: forecast & metrics \F" || echo "no changes"
          git push
      - name: Upload run log (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: out/run.log
